.TH "pyccuweather.objects.Hemiurnal" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.Hemiurnal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, json)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBsynopsis\fP"
.br
.ti -1c
.RI "\fBphrase\fP"
.br
.ti -1c
.RI "\fBsnow\fP"
.br
.ti -1c
.RI "\fBwind\fP"
.br
.ti -1c
.RI "\fBrain\fP"
.br
.ti -1c
.RI "\fBice\fP"
.br
.ti -1c
.RI "\fBtotal_liquid\fP"
.br
.ti -1c
.RI "\fBh_precipitation\fP"
.br
.ti -1c
.RI "\fBh_rain\fP"
.br
.ti -1c
.RI "\fBcloud_cover\fP"
.br
.ti -1c
.RI "\fBp_rain\fP"
.br
.ti -1c
.RI "\fBp_snow\fP"
.br
.ti -1c
.RI "\fBp_ice\fP"
.br
.ti -1c
.RI "\fBp_thunderstorm\fP"
.br
.ti -1c
.RI "\fBp_precipitation\fP"
.br
.ti -1c
.RI "\fBwind_gust\fP"
.br
.ti -1c
.RI "\fBraw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
