.TH "pyccuweather.objects.AirQualityFactor" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.AirQualityFactor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, aqf_dict)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBcategory\fP"
.br
.ti -1c
.RI "\fBband\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
