.TH "pyccuweather.objects.Wind" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.Wind \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBkmh\fP (self)"
.br
.ti -1c
.RI "def \fBmph\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBspeed\fP"
.br
.ti -1c
.RI "\fBunits\fP"
.br
.ti -1c
.RI "\fBhdg\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
