.TH "pyccuweather.objects.DailyForecasts" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.DailyForecasts \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, json)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeffective_date\fP"
.br
.ti -1c
.RI "\fBeffective_epoch_date\fP"
.br
.ti -1c
.RI "\fBend_date\fP"
.br
.ti -1c
.RI "\fBend_epoch_date\fP"
.br
.ti -1c
.RI "\fBseverity\fP"
.br
.ti -1c
.RI "\fBsynopsis\fP"
.br
.ti -1c
.RI "\fBlink\fP"
.br
.ti -1c
.RI "\fBmobile_link\fP"
.br
.ti -1c
.RI "\fBforecasts\fP"
.br
.ti -1c
.RI "\fBraw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
