.TH "pyccuweather.objects.LocationSet" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.LocationSet \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__len__\fP (self)"
.br
.ti -1c
.RI "def \fB__getitem__\fP (self, item)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBappend\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBresults\fP"
.br
.ti -1c
.RI "\fBsearch_expression\fP"
.br
.ti -1c
.RI "\fBcountry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a set of Locations returned usually as a search result.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
