.TH "pyccuweather.errors.UnauthorisedError" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.errors.UnauthorisedError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised when the connection was not authorised.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
