.TH "pyccuweather.objects.DegreeDay" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.DegreeDay \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, aqf_dict)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcooling\fP"
.br
.ti -1c
.RI "\fBwarming\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
