.TH "pyccuweather.objects.DailyForecast" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.DailyForecast \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, json)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBepoch_date\fP"
.br
.ti -1c
.RI "\fBdate\fP"
.br
.ti -1c
.RI "\fBtemp_min\fP"
.br
.ti -1c
.RI "\fBtemp_max\fP"
.br
.ti -1c
.RI "\fBrealfeel_temp_min\fP"
.br
.ti -1c
.RI "\fBrealfeel_temp_max\fP"
.br
.ti -1c
.RI "\fBrealfeel_shade_temp_min\fP"
.br
.ti -1c
.RI "\fBrealfeel_shade_temp_max\fP"
.br
.ti -1c
.RI "\fBhours_of_sun\fP"
.br
.ti -1c
.RI "\fBday\fP"
.br
.ti -1c
.RI "\fBnight\fP"
.br
.ti -1c
.RI "\fBraw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
