.TH "pyccuweather.objects.Precipitation" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.Precipitation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBmm\fP (self)"
.br
.ti -1c
.RI "def \fBinch\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBunits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a precipitation value.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pyccuweather\&.objects\&.Precipitation\&.inch ( self)"

.PP
.nf
Represents precipitation in inches.

:return: precipitation in in

.fi
.PP
 
.SS "def pyccuweather\&.objects\&.Precipitation\&.mm ( self)"

.PP
.nf
Represents precipitation in mm.

:return: precipitation in mm

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
