.TH "pyccuweather.objects.Region" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.Region \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBlocalized_name\fP"
.br
.ti -1c
.RI "\fBenglish_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An object representing an Accuweather Region.
For a list of Accuweather regions: http://apidev.accuweather.com/developers/regions

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
