.TH "pyccuweather.objects.Temperature" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.Temperature \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBF\fP (self)"
.br
.ti -1c
.RI "def \fBC\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBunits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a temperature value.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def pyccuweather\&.objects\&.Temperature\&.C ( self)"

.PP
.nf
Represents the Temperature in Celsius.

:return: Temperature in degrees Celsius.

.fi
.PP
 
.SS "def pyccuweather\&.objects\&.Temperature\&.F ( self)"

.PP
.nf
Represents the Temperature in Fahrenheit.

:return: Temperature in degrees Fahrenheit.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
