.TH "pyccuweather.objects.Location" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.Location \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlkey\fP"
.br
.ti -1c
.RI "\fBlat\fP"
.br
.ti -1c
.RI "\fBlon\fP"
.br
.ti -1c
.RI "\fBlocalized_name\fP"
.br
.ti -1c
.RI "\fBenglish_name\fP"
.br
.ti -1c
.RI "\fBregion\fP"
.br
.ti -1c
.RI "\fBcountry\fP"
.br
.ti -1c
.RI "\fBadministrative_area\fP"
.br
.ti -1c
.RI "\fBtimezone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a Location.
Locations are explained in the Accuweather documentation at http://apidev.accuweather.com/developers/locations

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
