.TH "pyccuweather.errors.MalformattedLocationKeyError" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.errors.MalformattedLocationKeyError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The location key is malformatted. This is raised when a primary (non-POI) location key is entered that does not fit
the formal specifications.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
