.TH "pyccuweather.objects.TimeZone" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.objects.TimeZone \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcode\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBgmt_offset\fP"
.br
.ti -1c
.RI "\fBis_daylight_saving\fP"
.br
.ti -1c
.RI "\fBnext_offset_change\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a timezone.
Timezones are explained in the Accuweather documentation at http://apidev.accuweather.com/developers/timeZones

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
