.TH "pyccuweather.errors.InvalidCountryCodeError" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.errors.InvalidCountryCodeError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, country_code)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcountry_code\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised when a country code is provided that does not exist.
Valid country codes are listed by Accuweather under http://apidev.accuweather.com/developers/countries

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
