.TH "pyccuweather.errors.MalformattedAPIKeyError" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.errors.MalformattedAPIKeyError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised when the API key looks malformatted (wrong type or length). Does not actually check the API key for validity!"

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
