.TH "pyccuweather.errors.NotImplementedOrUnknownMethod" 3 "Sat Jul 4 2015" "Version 0.31" "Pyccuweather" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyccuweather.errors.NotImplementedOrUnknownMethod \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, API_method)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAPI_method\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The method called has not been implemented yet or is an altogether non-existent method.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyccuweather from the source code\&.
